version: '2'
services:
    almoxarifado-app:
        image: almoxarifado
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://almoxarifado-mysql:3306/almoxarifado?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    almoxarifado-mysql:
        extends:
            file: mysql.yml
            service: almoxarifado-mysql
